backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: gna
    label: GNA 記事
    label_singular: GNA 記事
    folder: content/gna
    create: true
    slug: '{{slug}}'
    extension: md
    format: frontmatter
    fields:
      - { label: タイトル, name: title, widget: string }
      - {
          label: 日付,
          name: date,
          widget: datetime,
          format: YYYY-MM-DD,
          date_format: YYYY-MM-DD,
          time_format: false,
        }
      - { label: 要約, name: summary, widget: string, required: false }
      - { label: 下書き, name: draft, widget: boolean, default: false }
      - { label: 本文, name: body, widget: markdown }
